#
# Sub-system source	search path	for	Adjust_Dep at this dir level
#
# !!Customize!!	

export SSPATH =	$(SSMPATH)/src


#
# Extra	include	paths required by this module at this directory	level
#
# !!Customize!!	

EXTRA_HPATH	= -I$(SSPATH) -I$(SSMPATH)/inc
#EXTRA_HPATH =

EXTRA_CFLAGS =
EXTRA_CCFLAGS =	
EXTRA_ASFLAGS =	
CFLAGS +=


#
# Search path for GNU tool chain
#

VPATH =	$(LIB_PATH):$(SSOBJPATH)


#
# Object list at this directory	level
#
# !!Customize!!	

O_OBJS =	$(SSOBJPATH)/cmnos_tasklet.o


include	$(MAGPIE_ROOT)/build/make_opt/Rules.make

#
# The followings are automatically generated by	the	tool adj_dep
#

###	Dep	

/root/Workspace/0211/tgt/build/magpie_1_0/image/magpie_flash_boot/../../../..//build/magpie_1_0/rom/cmnos/tasklet/obj/cmnos_tasklet.o:  \
 /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/tasklet/src/cmnos_tasklet.c \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/sys_cfg.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/magpie/rom_cfg.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/magpie_mem.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/athos_api.h \
  /root/Workspace/0211/tgt/target/inc/osapi.h \
  /root/Workspace/0211/tgt/target/inc/OTUS/OTUS_soc.h \
  /root/Workspace/0211/tgt/target/inc/dt_defs.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/inc/cmnos_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/printf/inc/printf_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/uart/inc/uart_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/magpie/reg_defs.h \
  /root/Workspace/0211/tgt/target/cmnos/dbg/inc/dbg_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/mem/inc/mem_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/misc/inc/misc_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/string/inc/string_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/timer/inc/timer_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/rompatch/inc/romp_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/allocram/inc/allocram_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/tasklet/inc/tasklet_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/clock/inc/clock_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/intr/inc/intr_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/wdt/inc/wdt_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/eeprom/inc/eeprom_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/usb_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/hif_pci.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/hif_api.h \
  /root/Workspace/0211/tgt/adf/include/nbuf/adf_nbuf.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_util.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_util_pvt.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_types.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_stdtypes.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_types_pvt.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/vbuf/inc/vbuf_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/vdesc/inc/vdesc_api.h \
  /root/Workspace/0211/tgt/target/inc/stdarg.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_dma.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_dma_pvt.h \
  /root/Workspace/0211/tgt/adf/include/net/adf_net_types.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/adf/nbuf/inc/adf_nbuf_pvt.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/hif_gmac.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/Magpie_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/usbfifo_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/htc/inc/htc_api.h \
  /root/Workspace/0211/wlan/include/htc.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/buf_pool/inc/buf_pool_api.h \
  /root/Workspace/0211/tgt/target/wmi/inc/wmi_svc_api.h \
  /root/Workspace/0211/wlan/include/wmi.h \
  /root/Workspace/0211/wlan/include/athdefs.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/dma_engine/inc/dma_engine_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/dma_lib.h \
  /root/Workspace/0211/tgt/target/cmnos/sflash/inc/sflash_api.h
/root/Workspace/0211/tgt/build/magpie_1_0/image/magpie_flash_boot/../../../..//build/magpie_1_0/rom/cmnos/tasklet/obj/cmnos_tasklet.o:  \
 /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/tasklet/src/cmnos_tasklet.c \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/sys_cfg.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/magpie/rom_cfg.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/magpie_mem.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/athos_api.h \
  /root/Workspace/0211/tgt/target/inc/osapi.h \
  /root/Workspace/0211/tgt/target/inc/OTUS/OTUS_soc.h \
  /root/Workspace/0211/tgt/target/inc/dt_defs.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/inc/cmnos_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/printf/inc/printf_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/uart/inc/uart_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/magpie/reg_defs.h \
  /root/Workspace/0211/tgt/target/cmnos/dbg/inc/dbg_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/mem/inc/mem_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/misc/inc/misc_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/string/inc/string_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/timer/inc/timer_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/rompatch/inc/romp_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/allocram/inc/allocram_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/tasklet/inc/tasklet_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/clock/inc/clock_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/intr/inc/intr_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/wdt/inc/wdt_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/cmnos/eeprom/inc/eeprom_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/usb_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/hif_pci.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/hif_api.h \
  /root/Workspace/0211/tgt/adf/include/nbuf/adf_nbuf.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_util.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_util_pvt.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_types.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_stdtypes.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_types_pvt.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/vbuf/inc/vbuf_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/vdesc/inc/vdesc_api.h \
  /root/Workspace/0211/tgt/target/inc/stdarg.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_dma.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_dma_pvt.h \
  /root/Workspace/0211/tgt/adf/include/net/adf_net_types.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/adf/nbuf/inc/adf_nbuf_pvt.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/hif_gmac.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/inc/Magpie_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/usbfifo_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/htc/inc/htc_api.h \
  /root/Workspace/0211/wlan/include/htc.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/buf_pool/inc/buf_pool_api.h \
  /root/Workspace/0211/tgt/target/wmi/inc/wmi_svc_api.h \
  /root/Workspace/0211/wlan/include/wmi.h \
  /root/Workspace/0211/wlan/include/athdefs.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/dma_engine/inc/dma_engine_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/rom/hif/inc/dma_lib.h \
  /root/Workspace/0211/tgt/target/cmnos/sflash/inc/sflash_api.h
/root/Workspace/0211/tgt/build/magpie_1_0/image/magpie_flash_boot/../../../..//build/magpie_1_0/sflash_boot/cmnos/tasklet/obj/cmnos_tasklet.o:  \
 /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/tasklet/src/cmnos_tasklet.c \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/inc/sys_cfg.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/inc/magpie/rom_cfg.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/inc/magpie_mem.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/inc/athos_api.h \
  /root/Workspace/0211/tgt/target/inc/osapi.h \
  /root/Workspace/0211/tgt/target/inc/OTUS/OTUS_soc.h \
  /root/Workspace/0211/tgt/target/inc/dt_defs.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/inc/cmnos_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/printf/inc/printf_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/uart/inc/uart_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/inc/magpie/reg_defs.h \
  /root/Workspace/0211/tgt/target/cmnos/dbg/inc/dbg_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/mem/inc/mem_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/misc/inc/misc_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/string/inc/string_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/timer/inc/timer_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/rompatch/inc/romp_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/allocram/inc/allocram_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/tasklet/inc/tasklet_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/clock/inc/clock_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/intr/inc/intr_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/wdt/inc/wdt_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/cmnos/eeprom/inc/eeprom_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/hif/inc/usb_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/hif/inc/hif_pci.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/hif/inc/hif_api.h \
  /root/Workspace/0211/tgt/adf/include/nbuf/adf_nbuf.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_util.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_util_pvt.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_types.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_stdtypes.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_types_pvt.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/vbuf/inc/vbuf_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/vdesc/inc/vdesc_api.h \
  /root/Workspace/0211/tgt/target/inc/stdarg.h \
  /root/Workspace/0211/tgt/adf/include/os/adf_os_dma.h \
  /root/Workspace/0211/tgt/target/adf/os/inc/adf_os_dma_pvt.h \
  /root/Workspace/0211/tgt/adf/include/net/adf_net_types.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/adf/nbuf/inc/adf_nbuf_pvt.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/hif/inc/hif_gmac.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/inc/Magpie_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/hif/inc/usbfifo_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/htc/inc/htc_api.h \
  /root/Workspace/0211/wlan/include/htc.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/buf_pool/inc/buf_pool_api.h \
  /root/Workspace/0211/tgt/target/wmi/inc/wmi_svc_api.h \
  /root/Workspace/0211/wlan/include/wmi.h \
  /root/Workspace/0211/wlan/include/athdefs.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/dma_engine/inc/dma_engine_api.h \
  /root/Workspace/0211/tgt/build/magpie_1_0/sflash_boot/hif/inc/dma_lib.h \
  /root/Workspace/0211/tgt/target/cmnos/sflash/inc/sflash_api.h
