#!/usr/bin/env python2
if __name__ == "__main__":
    import sys
    import pyrit_cli
    try:
        pyrit_cli.Pyrit_CLI().initFromArgv()
    except (KeyboardInterrupt, SystemExit):
        print("\nInterrupted...")
    except pyrit_cli.PyritRuntimeError as e:
        sys.exit(e)
